/*
  station_meteo_tinyml.ino
  - Lecture DHT11 + LDR
  - Affichage OLED
  - Envoi ThingSpeak
  - TinyML inference (TFLite Micro) : prédiction température future
  - Alerte locale (LED + Buzzer) basée sur valeur mesurée ET prédite
*/

// === INCLUDES matériel / réseau / capteurs / écran ===


#include <WiFi.h>
#include <HTTPClient.h>
#include <Adafruit_Sensor.h>
#include <DHT.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

// === TFLite for Microcontrollers includes ===
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/version.h"

// === Paramètres WiFi / ThingSpeak ===
const char* ssid = "TOPNET_BCC0";
const char* password = "5tr6ah66as";
String apiKey = "KU1PNQ2YYLU4CC9K";
const char* server = "http://api.thingspeak.com/update";

// === Capteurs / broches ===
#define DHTPIN 15
#define DHTTYPE DHT11
DHT dht(DHTPIN, DHTTYPE);

#define LDRPIN 34
#define LEDPIN 2
#define BUZZERPIN 13

// Seuil d'alerte (mesuré ou prédit)
#define TEMP_ALERT 25.0

// === OLED ===
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

// === TFLite model (model.cc generated by xxd) ===
// Generate model.cc: xxd -i model.tflite > model.cc
extern const unsigned char model_tflite[];  // fourni par model.cc
extern const unsigned int model_tflite_len;

// === TFLM runtime globals ===
const int kTensorArenaSize = 12 * 1024; // Ajuster si OOM (augmenter si possible)
static uint8_t tensor_arena[kTensorArenaSize];

tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input_tensor = nullptr;
TfLiteTensor* output_tensor = nullptr;

// === Fenêtre glissante (doit correspondre à N_STEPS utilisé pour l'entraînement) ===
const int N_STEPS = 6; // DOIT correspondre à ton training
float window_vals[N_STEPS];
bool window_filled = false;

// === Paramètres de normalisation (remplacer par les valeurs réelles de training) ===
float mean_train = 23.0; // <-- remplacer par mean réel
float std_train  = 2.0;  // <-- remplacer par std réel

// === Timers ===
unsigned long last_read_ms = 0;
unsigned long last_send_ms = 0;
const unsigned long READ_INTERVAL = 10000;   // 10s lecture capteurs local
const unsigned long SEND_INTERVAL = 30000;   // 30s envoi ThingSpeak (OK pour prototype)

// === Fonctions utilitaires OLED ===
void showOLEDlines(const char* l1, const char* l2 = "", const char* l3 = "", const char* l4 = "") {
  display.clearDisplay();
  display.setCursor(0, 0);
  display.println(l1);
  if (l2[0]) display.println(l2);
  if (l3[0]) display.println(l3);
  if (l4[0]) display.println(l4);
  display.display();
}

// === push in sliding window ===
void push_window(float new_val) {
  // shift left
  for (int i = 0; i < N_STEPS - 1; ++i) window_vals[i] = window_vals[i+1];
  window_vals[N_STEPS - 1] = new_val;
  // check filled
  static int count = 0;
  if (count < N_STEPS) count++;
  if (count >= N_STEPS) window_filled = true;
}

// === Initialisation TFLM ===
bool init_tflm() {
  const tflite::Model* model = tflite::GetModel(model_tflite);
  if (model == nullptr) {
    Serial.println("Erreur: model_tflite == nullptr");
    return false;
  }
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    Serial.println("Erreur: Schema version mismatch");
    return false;
  }
  static tflite::AllOpsResolver resolver;
  static tflite::MicroInterpreter static_interpreter(
    model, resolver, tensor_arena, kTensorArenaSize, nullptr);
  interpreter = &static_interpreter;
  TfLiteStatus alloc_status = interpreter->AllocateTensors();
  if (alloc_status != kTfLiteOk) {
    Serial.println("Erreur: AllocateTensors() failed");
    return false;
  }
  input_tensor = interpreter->input(0);
  output_tensor = interpreter->output(0);
  Serial.println("TFLite model chargé et tenseurs alloués.");
  Serial.print("Input tensor type: "); Serial.println(input_tensor->type);
  Serial.print("Output tensor type: "); Serial.println(output_tensor->type);
  // Print quant params for debugging
  Serial.print("Input scale: "); Serial.println(input_tensor->params.scale, 9);
  Serial.print("Input zero_point: "); Serial.println(input_tensor->params.zero_point);
  Serial.print("Output scale: "); Serial.println(output_tensor->params.scale, 9);
  Serial.print("Output zero_point: "); Serial.println(output_tensor->params.zero_point);
  return true;
}

// === Run inference and return predicted temperature (Celsius) or NAN if not ready ===
float run_inference_prediction() {
  if (!window_filled) return NAN;
  if (input_tensor == nullptr || output_tensor == nullptr) return NAN;

  // Fill input tensor depending on type
  if (input_tensor->type == kTfLiteInt8) {
    float in_scale = input_tensor->params.scale;
    int in_zp = input_tensor->params.zero_point;
    for (int i = 0; i < N_STEPS; ++i) {
      float normalized = (window_vals[i] - mean_train) / std_train; // same normalization as training
      int32_t q = (int32_t) round(normalized / in_scale) + in_zp;
      if (q < -128) q = -128; if (q > 127) q = 127;
      input_tensor->data.int8[i] = (int8_t) q;
    }
  } else if (input_tensor->type == kTfLiteFloat32) {
    for (int i = 0; i < N_STEPS; ++i) {
      float normalized = (window_vals[i] - mean_train) / std_train;
      input_tensor->data.f[i] = normalized;
    }
  } else {
    Serial.println("Type input tensor non supporté");
    return NAN;
  }

  unsigned long t0 = micros();
  TfLiteStatus invoke_status = interpreter->Invoke();
  unsigned long dt = micros() - t0;
  if (invoke_status != kTfLiteOk) {
    Serial.println("Erreur Invoke()");
    return NAN;
  }
  // Read output and de-normalize
  float pred = NAN;
  if (output_tensor->type == kTfLiteInt8) {
    int8_t q = output_tensor->data.int8[0];
    float norm = (float)(q - output_tensor->params.zero_point) * output_tensor->params.scale;
    pred = norm * std_train + mean_train;
  } else if (output_tensor->type == kTfLiteFloat32) {
    float norm = output_tensor->data.f[0];
    pred = norm * std_train + mean_train;
  } else {
    Serial.println("Type output tensor non supporté");
    return NAN;
  }

  Serial.print("Inference done in (us): "); Serial.println(dt);
  return pred;
}

// === Setup ===
void setup() {
  Serial.begin(115200);
  delay(100);

  // Capteurs & periph
  dht.begin();
  pinMode(LDRPIN, INPUT);
  pinMode(LEDPIN, OUTPUT);
  pinMode(BUZZERPIN, OUTPUT);
  digitalWrite(LEDPIN, LOW);
  noTone(BUZZERPIN);

  // OLED init
  if (!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
    Serial.println("Erreur initialisation OLED !");
    for (;;); // blocage si ecran absent
  }
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  showOLEDlines("Station Meteo", "", "Init...");

  // WiFi
  showOLEDlines("Connexion Wi-Fi...");
  WiFi.begin(ssid, password);
  unsigned long start = millis();
  while (WiFi.status() != WL_CONNECTED) {
    delay(300);
    Serial.print(".");
    if (millis() - start > 20000) {
      Serial.println("\nEchec connexion Wi-Fi, retry...");
      WiFi.disconnect();
      WiFi.begin(ssid, password);
      start = millis();
    }
  }
  Serial.println("\nWi-Fi connecte !");
  showOLEDlines("Wi-Fi OK", WiFi.localIP().toString().c_str());
  delay(800);

  // Init TFLM (tentative — si model.cc absent, init_tflm() échouera)
  bool ok = init_tflm();
  if (!ok) {
    Serial.println("Attention : TFLM non initialisé (model manquant ou erreur). Le sketch fonctionne sans inference.");
    showOLEDlines("TFLM non initialise", "Verif model.cc");
  } else {
    showOLEDlines("TFLM OK", "Inference activée");
  }
}

// === Loop principal ===
void loop() {
  unsigned long now = millis();

  // Lecture capteurs toutes les READ_INTERVAL
  if (now - last_read_ms >= READ_INTERVAL) {
    last_read_ms = now;

    float temp = dht.readTemperature();
    float hum  = dht.readHumidity();
    int ldrRaw = analogRead(LDRPIN);
    float lightPercent = (ldrRaw / 4095.0) * 100.0;

    if (isnan(temp) || isnan(hum)) {
      Serial.println("Erreur lecture DHT11 !");
      showOLEDlines("Erreur lecture DHT11", "Reessai dans 5s");
      delay(5000);
      return;
    }

    // Affichage local (on mettra plus tard la prédiction si dispo)
    char buf1[32], buf2[32], buf3[32];
    snprintf(buf1, sizeof(buf1), "Temp: %.1f C", temp);
    snprintf(buf2, sizeof(buf2), "Hum:  %.1f %%", hum);
    snprintf(buf3, sizeof(buf3), "Lumi: %.0f %%", lightPercent);
    showOLEDlines("Station Meteo Int.", buf1, buf2, buf3);

    // Alarme locale selon mesure
    if (temp > TEMP_ALERT) {
      digitalWrite(LEDPIN, HIGH);
      tone(BUZZERPIN, 1000, 300);
    } else {
      digitalWrite(LEDPIN, LOW);
      noTone(BUZZERPIN);
    }

    // PUSH dans la fenêtre et tenter une inference
    push_window(temp);
    float pred_temp = run_inference_prediction(); // NaN si pas prêt

    if (!isnan(pred_temp)) {
      Serial.print("Prediction T+: "); Serial.println(pred_temp);
      char predBuf[32];
      snprintf(predBuf, sizeof(predBuf), "Pred T+: %.1f C", pred_temp);
      showOLEDlines("Station Meteo Int.", buf1, buf2, predBuf);

      // Alerte si la température prédite dépasse seuil
      if (pred_temp > TEMP_ALERT) {
        digitalWrite(LEDPIN, HIGH);
        tone(BUZZERPIN, 1200, 400);
      }
    } else {
      Serial.println("Prediction non disponible (fenetre pas encore remplie)");
    }

    // Envoi ThingSpeak (toutes les SEND_INTERVAL)
    if (now - last_send_ms >= SEND_INTERVAL) {
      last_send_ms = now;
      if (WiFi.status() == WL_CONNECTED) {
        HTTPClient http;
        String url = String(server) + "?api_key=" + apiKey +
                     "&field1=" + String(temp, 1) +
                     "&field2=" + String(hum, 1) +
                     "&field3=" + String((int)lightPercent);
        if (!isnan(pred_temp)) url += "&field4=" + String(pred_temp, 1);
        Serial.println("Envoi TS: " + url);
        http.begin(url);
        int httpCode = http.GET();
        Serial.print("httpCode = "); Serial.println(httpCode);
        if (httpCode > 0) {
          String payload = http.getString();
          Serial.println("Payload: " + payload);
          if (httpCode >= 200 && httpCode < 300) {
            Serial.println("✅ Donnees envoyees sur ThingSpeak !");
          } else {
            Serial.println("Erreur HTTP serveur, code: " + String(httpCode));
            showOLEDlines("Erreur HTTP", ("Code: " + String(httpCode)).c_str());
          }
        } else {
          Serial.println("❌ Erreur HTTP client");
          showOLEDlines("Erreur HTTP", "Client failed");
        }
        http.end();
      } else {
        Serial.println("Wi-Fi deconnecte, envoi annulé");
        showOLEDlines("Wi-Fi deconnecte");
      }
    } // fin envoi
  } // fin lecture capteurs

  delay(20); // petite pause non bloquante
}
